### ISSUE TITLE
bibdata refactor changes

### ISSUE THREAD

**Issue by opoudjis** [metanorma/nistbib#15]
The following changes impact this gem, as elements moved to bibdata/ext from bibitem. All elements specific to NIST must be populated in bibdata/ext; please ask me if there are any changes not covered in the following.

The grammar of ext is:

````
DocumentType =
        "standard"

editorialgroup = element editorialgroup {
  committee+
}

bkeyword = element keyword { text }

commentperiod = element commentperiod {
element from { ISO8601Date },
element to { ISO8601Date }?,
element extended { ISO8601Date }?
}

BibDataExtensionType =
    doctype?, bkeyword+, commentperiod?

````

* The type of standard, e.g. "recommendation", is no longer set in `bibitem/@type`. It is now set in `bibdata/ext/doctype`

* `keyword`, and `recommendationstatus` are all set in `bibdata/ext`

* Note in edition: the element `revision` is no longer used. Instead, revision numbers shall appear in the `edition` element, prefixed with "Revision"; e.g. Revision 1 = `<edition>Revision 1</edition>`

**Comment by andrew2net** [comment]
@opoudjis I see `editorialgroup` definition only? Where do we use the definition?

**Comment by opoudjis** [comment]
Answered offline

**Comment by ronaldtse** [comment]
@opoudjis what is `editorialgroup` used for? It's not in the Relaton-NIST model: https://raw.githubusercontent.com/metanorma/metanorma-model-nist/master/images/nist-bibliographic-item.png

**Comment by opoudjis** [comment]
Answered offline

**Comment by opoudjis** [comment]
It isn't. It was, and I hadn't taken the definition out, but I had taken out its instance in bibdata. I've removed the definition now too.
