### ISSUE TITLE
Integrate NistBib into Metanorma

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/nistbib#3]
For @opoudjis . Thanks!

The syntax will be something like:
* "NIST XXXX" such as "NIST SP 800-53"
* "NISTIR XXXX" such as "NISTIR 7628"
* see the "NistPubSeries" class at https://github.com/metanorma/metanorma-model-nist

**Comment by opoudjis** [comment]
Adding the following Series abbreviations as recognised NIST prefixes:

NISTGCR
ITL Bulletin
JPCRD
NISTIR
CSRC
